# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-24 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('token', models.CharField(default=b'1837a749-67ec-40f1-a4ee-fab50c20c265', max_length=70, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('loggedout_time', models.DateTimeField(null=True)),
                ('is_logged_in', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=1024, null=True)),
                ('mname', models.CharField(max_length=1024, null=True)),
                ('lname', models.CharField(max_length=1024, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('password', models.CharField(max_length=1024)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('loggins', models.ManyToManyField(related_name='user_loggins', to='user_models.Login')),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_models.User'),
        ),
    ]
